### PR TITLE
Fix handling case where ghsign.json doesn't exist

### PR DESCRIPTION
**Pull request by omphalos**
@mafintosh this fixes issue #11.

### CODE REVIEW

**Comment by watson** [comment]
In case `ghsign.json` does exists but `fs.readFile` returns an error due to something else, it would be better to wrap the `fs.readFile` in a `fs.exists` I think

**Comment by mafintosh** [comment]
@watson we can check `err.code === 'ENOENT'` for that

**Comment by omphalos** [comment]
@mafintosh @watson I've modified this so that errors that aren't ENOENT will get propagated as before.

**Comment by mafintosh** [comment]
Released in 3.0.2

**Pull request merged**
